version: "3"
services:
  gatsby:
    image: gatsby-blog:emb09
    container_name: gatsby-blog
    build:
      context: ./gatsby-docker
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Tokyo
    working_dir: /app
    volumes:
      - ./gatsby-docker/blog:/app
      - node_modules:/app/node_modules
    # entrypoint: "gatsby develop --host=0.0.0.0"
    entrypoint: "sh -c 'pwd && ls -la && yarn install && yarn start'"

volumes:
  node_modules:
    driver: "local"
