version: "3"
services:
  gatsby:
    image: gatsby-blog:prd
    container_name: gatsby-blog
    build:
      context: ./gatsby-docker
      dockerfile: Dockerfile-prd
    restart: always
    ports:
      - 80:80
    environment:
      TZ: Asia/Tokyo
    # working_dir: /app
#     volumes:
#       - ./blog:/app
#       - node_modules:/app/node_modules
#     # entrypoint: "gatsby develop --host=0.0.0.0"
#     entrypoint: "sh -c 'yarn install && yarn start'"

# volumes:
#   node_modules:
#     driver: "local"
