FROM node:12.10.0-alpine AS build-deps

RUN npm install -g gatsby-cli

ENV NODE_ENV=production

WORKDIR /app

COPY ./blog/package.json ./
COPY ./blog/yarn.lock ./
RUN yarn install

COPY ./blog ./


RUN gatsby build

RUN ls  ./ | xargs echo

FROM nginx:1.12-alpine
COPY --from=build-deps /app/public /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
